# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
substitutions:
  _IMAGE_NAME: ekgf/terraform
  _IMAGE_VERSION: latest
  _MANUALLY_INCREMENTED_IMAGE_VERSION: "0.1"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --tag
  - ${_IMAGE_NAME}:${_MANUALLY_INCREMENTED_IMAGE_VERSION}
  - --tag
  - ${_IMAGE_NAME}:${_IMAGE_VERSION}
  - .
- name: '${_IMAGE_NAME}:${_MANUALLY_INCREMENTED_IMAGE_VERSION}'
  args: ['version']

images:
  - '${_IMAGE_NAME}:${_MANUALLY_INCREMENTED_IMAGE_VERSION}'
  - '${_IMAGE_NAME}:${_IMAGE_VERSION}'

  tags: ['cloud-builders-community']
