name: build-image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

      - name: Checkout ekgf/gloud-terraform
        uses: actions/checkout@v4

      - name: set-env
        run: |
          echo "FQ_IMAGE_NAME=${{ vars.FQ_IMAGE_NAME }}" >> $GITHUB_ENV
          echo "VERSION=$(< ./VERSION)" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          #
          # TODO: Get the version number from a file (for instance localbuild.sh) or "/VERSION"
          #
          tags: ${{ env.FQ_IMAGE_NAME }}:latest, ${{ env.FQ_IMAGE_NAME }}:${{ env.VERSION }}
          pull: true
